In [2]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [4]:
#loading dataset
data = pd.read_csv('bse_dataset.csv')

In [5]:
data

,Timestamp,What is your gender?,Age,What is your emotion?,Year of birth,What is your CGPA?,Do you have a Girl Friend or BOY Friend,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you have seek any specialist for a treatment?
0,05/07/2023 09:38:39,Male,21,Content,2002,4.22,No,No,Yes,Yes,Yes
1,05/07/2023 09:38:57,Marabou stock,45,Weird,2100,8.9,Yes,Yes,Yes,Yes,No
2,05/07/2023 09:39:09,Female,20,Happy,2002,3.98,No,No,Yes,Yes,No
3,05/07/2023 09:39:12,Male,21,Happy,2003,4.37,No,No,No,No,Nope
4,05/07/2023 09:39:14,Female,21,Happy,2002,3.63,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...
92,05/07/2023 09:53:56,Female,68,Sad,1953,4.8,No,Yes,Yes,Yes,Yes
93,05/07/2023 09:54:13,Male,29,Hopeful,1994,I don't know yet,"Sure, multiple girlfriends",No,No,No,No
94,05/07/2023 09:54:28,Male,22,Fighting poverty,2001,3.12,Girl friends are thieves,Yes,Yes,No,No
95,05/07/2023 09:54:36,Male,23,good and bad,2000,3.5,Namiiro Zahara Bidin,No,No,No,No
96,05/07/2023 09:54:52,male,30,hunger,2023,5,ARI,no,yeah,nah,yeah

In [7]:
#first things first shape of the data number of raws and columns
data.shape

(97, 11)

In [8]:
data.columns

Index(['Timestamp', 'What is your gender?', 'Age', 'What is your emotion?',
       'Year of birth', 'What is your CGPA?',
       'Do you have a Girl Friend or BOY Friend', 'Do you have Depression?',
       'Do you have Anxiety?', 'Do you have Panic attack?',
       'Did you have seek any specialist for a treatment? '],
      dtype='object')

In [11]:
#getting information about the dataset that is the datatypes
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 11 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Timestamp                                           97 non-null     object
 1   What is your gender?                                97 non-null     object
 2   Age                                                 97 non-null     int64
 3   What is your emotion?                               96 non-null     object
 4   Year of birth                                       97 non-null     object
 5   What is your CGPA?                                  97 non-null     object
 6   Do you have a Girl Friend or BOY Friend             97 non-null     object
 7   Do you have Depression?                             97 non-null     object
 8   Do you have Anxiety?                                97 non-null     object
 9   Do you have Panic attack?                           97 non-null     object
 10  Did you have seek any specialist for a treatment?   97 non-null     object
dtypes: int64(1), object(10)
memory usage: 8.5+ KB

HANDLING MISSING DATA

In [15]:
data.isnull()  # Returns a Boolean DataFrame indicating missing values
data.isnull().sum()  # Returns the count of missing values in each column

Timestamp                                             0
What is your gender?                                  0
Age                                                   0
What is your emotion?                                 1
Year of birth                                         0
What is your CGPA?                                    0
Do you have a Girl Friend or BOY Friend               0
Do you have Depression?                               0
Do you have Anxiety?                                  0
Do you have Panic attack?                             0
Did you have seek any specialist for a treatment?     0
dtype: int64

In [19]:
data.dropna()  # Drops rows with any missing values
dag=data.dropna(subset=['What is your emotion?'])  # Drops rows with missing values in specific columns
dag

,Timestamp,What is your gender?,Age,What is your emotion?,Year of birth,What is your CGPA?,Do you have a Girl Friend or BOY Friend,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you have seek any specialist for a treatment?
0,05/07/2023 09:38:39,Male,21,Content,2002,4.22,No,No,Yes,Yes,Yes
1,05/07/2023 09:38:57,Marabou stock,45,Weird,2100,8.9,Yes,Yes,Yes,Yes,No
2,05/07/2023 09:39:09,Female,20,Happy,2002,3.98,No,No,Yes,Yes,No
3,05/07/2023 09:39:12,Male,21,Happy,2003,4.37,No,No,No,No,Nope
4,05/07/2023 09:39:14,Female,21,Happy,2002,3.63,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...
92,05/07/2023 09:53:56,Female,68,Sad,1953,4.8,No,Yes,Yes,Yes,Yes
93,05/07/2023 09:54:13,Male,29,Hopeful,1994,I don't know yet,"Sure, multiple girlfriends",No,No,No,No
94,05/07/2023 09:54:28,Male,22,Fighting poverty,2001,3.12,Girl friends are thieves,Yes,Yes,No,No
95,05/07/2023 09:54:36,Male,23,good and bad,2000,3.5,Namiiro Zahara Bidin,No,No,No,No
96,05/07/2023 09:54:52,male,30,hunger,2023,5,ARI,no,yeah,nah,yeah

In [20]:
dag.isnull().sum()

Timestamp                                             0
What is your gender?                                  0
Age                                                   0
What is your emotion?                                 0
Year of birth                                         0
What is your CGPA?                                    0
Do you have a Girl Friend or BOY Friend               0
Do you have Depression?                               0
Do you have Anxiety?                                  0
Do you have Panic attack?                             0
Did you have seek any specialist for a treatment?     0
dtype: int64

In [26]:
dat=data.fillna('sad')  # Replace missing values with a specific value
#date=data.fillna(data.mean())  # Replace missing values with the mean of the column
dat
#date

/tmp/ipykernel_16095/1041649090.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  date=data.fillna(data.mean())  # Replace missing values with the mean of the column

,Timestamp,What is your gender?,Age,What is your emotion?,Year of birth,What is your CGPA?,Do you have a Girl Friend or BOY Friend,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you have seek any specialist for a treatment?
0,05/07/2023 09:38:39,Male,21,Content,2002,4.22,No,No,Yes,Yes,Yes
1,05/07/2023 09:38:57,Marabou stock,45,Weird,2100,8.9,Yes,Yes,Yes,Yes,No
2,05/07/2023 09:39:09,Female,20,Happy,2002,3.98,No,No,Yes,Yes,No
3,05/07/2023 09:39:12,Male,21,Happy,2003,4.37,No,No,No,No,Nope
4,05/07/2023 09:39:14,Female,21,Happy,2002,3.63,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...
92,05/07/2023 09:53:56,Female,68,Sad,1953,4.8,No,Yes,Yes,Yes,Yes
93,05/07/2023 09:54:13,Male,29,Hopeful,1994,I don't know yet,"Sure, multiple girlfriends",No,No,No,No
94,05/07/2023 09:54:28,Male,22,Fighting poverty,2001,3.12,Girl friends are thieves,Yes,Yes,No,No
95,05/07/2023 09:54:36,Male,23,good and bad,2000,3.5,Namiiro Zahara Bidin,No,No,No,No
96,05/07/2023 09:54:52,male,30,hunger,2023,5,ARI,no,yeah,nah,yeah

In [22]:
dat.isnull().sum()

Timestamp                                             0
What is your gender?                                  0
Age                                                   0
What is your emotion?                                 0
Year of birth                                         0
What is your CGPA?                                    0
Do you have a Girl Friend or BOY Friend               0
Do you have Depression?                               0
Do you have Anxiety?                                  0
Do you have Panic attack?                             0
Did you have seek any specialist for a treatment?     0
dtype: int64

HANDLING DUPLICATES

In [27]:
data.duplicated()  # Returns a Boolean Series indicating duplicate rows
#data.drop_duplicates()  # Drops duplicate rows

0     False
1     False
2     False
3     False
4     False
      ...
92    False
93    False
94    False
95    False
96    False
Length: 97, dtype: bool